name: Bug Report
description: Submit a bug report
title: "[Bug Fix] "
labels: "bug" #issue labels
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report form!
  - type: checkboxes
    id: checklist
    attributes:
      label: Submition Checklist
      options:
        - label: I have read the [Code of Conduct](./CODE-OF-CONDUCT.md)
          required: true
        - label: I have checked other issues for similar bugs
          required: true
  - type: input
    id: bug-title
    attributes:
      label: What is a short description of the bug?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: What is the bug?
      placeholder: Please make sure to be specific
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: What is the expected behavior?
    validations:
      required: true
  - type: textarea
    id: bug-current
    attributes:
      label: What is the current behavior?
    validations:
      required: true