blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: ./SECURITY.md
    about: Get details on how to report a security issue.
  - name: Code of Conduct
    url: ./CODE-OF-CONDUCT.md
    about: Read our code of conduct.
  - name: Contributing
    url: ./CONTRIBUTING.md
    about: Learn how to contribute to this project.
  - name: Support
    url: mailto:benpai@sparty182020.com
    about: Get help with this project.